name: Ruby Gem

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "5 * * * *"

jobs:
  rebuild:
    runs-on: macos-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Build
        run: |
          ./make.sh
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
